### PR TITLE
Added Monolog

### PR DESCRIPTION
**Pull request by alexbilbie**

### CODE REVIEW

**Comment by alexbilbie** [comment]
@sagikazarmark

**Comment by sagikazarmark** [comment]
What's the point of having multiple loggers? I can't think of any use case, but even if I could, it is some sort of container logic.

IMO logger object should be injected into the service using it (or created like in case of Application container and route collection), thus a logic like this has no valid use case as I can see.

I would also like to see `LoggerAwareInterface` implemented (if possible, currently not).

**Comment by alexbilbie** [comment]
Regarding multiple loggers see this explanation here - https://github.com/Seldaek/monolog/blob/master/doc/usage.md#leveraging-channels

**Comment by sagikazarmark** [comment]
Then the `getLogger` name is a bit confusing IMO.

**Comment by alexbilbie** [comment]
In my own usecase at work I have multiple loggers - some that go to Hipchat, others into files, others that are a stream of consciousness

**Comment by alexbilbie** [comment]
Why is a bit confusing? You're getting a logger with a specific name, it doesn't matter if it's already created or not because you'll always receive one.

**Comment by sagikazarmark** [comment]
You are probably right. I was thinking about logger as a dependency from the class point of view.

I am thinking about if this channel thing can be made optional:

``` php
use Monolog\Logger;

class Application
{
	/**
	 * @var array
	 */
	protected $loggers = [];

	/**
	 * Return a logger
	 *
	 * @return \Monolog\Logger
	 */
	public function getLogger($name = 'default')
	{
		if (isset($this->loggers[$name])) {
			return $this->loggers[$name];
		}

		$logger = new Logger($name);
		$this->loggers[$name] = $logger;

		return $logger;
	}

	/**
	 * Set a logger
	 *
	 * @param $logger \Monolog\Logger
	 */
	public function setLogger(Logger $logger)
	{
		$this->loggers[$logger->getName()] = $logger;
	}
}
```

**Comment by sagikazarmark** [comment]
The setter is probably useless. Just followed the setter-getter pattern.

**Comment by sagikazarmark** [comment]
Ah, I am a super-monkey, I've rewritten the exact some code as you did. It's late. ;)

Anyway, making the `$name` in `getLogger` optional could make this feature optional. It is not alway used IMO.

**Pull request merged**
