### PR TITLE
Added log function to Application with Documentation and Tests

### PR DESCRIPTION
**Pull request by ry167**
I added an easier `log` function and mimicked Monolog's own test for it.

Sorry for the different brace style, I can fix that if you want me too.

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
I'm not a fan of this. You can access the logger via `getLogger()`, which then returns an implementation of PSR loggerinterface. No need to let the application class implement kind of part of the loggerinterface.

**Comment by ry167** [comment]
All good, I figured I would just suggest it as a shorter method like the route ones

**Comment by hannesvdvreken** [comment]
Suggesting is always good ;-) plus, it's not my call.

**Comment by sagikazarmark** [comment]
I'm not a fan of this either. It is much harder than using `getLogger` if you make use of channels.

**Comment by alexbilbie** [comment]
I'm going to reject this because as @sagikazarmark said it makes it harder to use channels. Thanks though for the suggestion.

**Pull request closed without merging**
