### PR TITLE
Type hint psr logger interface

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
What's wrong with scrutinizer?

**Comment by sagikazarmark** [comment]
This is invalid. It will never return anything, but a Monolog instance. Why typehint it the interface then?

**Comment by hannesvdvreken** [comment]
I thought it would be better to prepare for change, that's why I suggested this. The user doesn't need to use any monolog specific methods, the user just needs to log stuf. Interface segregation principle. No big deal if this PR gets denied.

**Comment by sagikazarmark** [comment]
Since Proton does not support any other logger than Monolog, IMO it is rather confusing.

**Comment by alexbilbie** [comment]
Merging this on the basis that Monolog could be swapped out by a user if they wanted

**Pull request merged**
